#goal definition
#the lines with the hash signs are merely comments
#goal, result and feedback are defined by this fixed order, and separated by 3 hyphens

#define messages constants:

int32 TOP_ACTION_CLIENT=1                                                                 #
int32 MID_ACTION_CLIENT=2                                                                 #
int32 BOTTOM_ACTION_CLIENT=3                                                              #

#goal messages:
geometry_msgs/PointStamped entry_point                                                    # needle entry point position
geometry_msgs/PointStamped exit_point                                                     # needle exit point position
geometry_msgs/TransformStamped grasp_transform                                            # grasp transform btw gripper and needle
float64 depth_of_suture                                                                   # suture depth
float64 needle_radius                                                                     # needle radius
int32 arm_indication                                                                      # arm index
int32 which_action_client                                                                 # which action client to be use
---
#result definition
cwru_davinci_msgs/ListOfPointStamped exit_points_list                                     # a list needle exit points' position
cwru_davinci_msgs/ListOfJointTrajectory joint_trajectory_list                             # a list of valid joint trajectory
cwru_davinci_msgs/ListOfTransformStamped valid_grasp_transform_list                       # a list of valid grasp transform
geometry_msgs/PointStamped selected_exit_point                                            # a valid exit point position
trajectory_msgs/JointTrajectory valid_trajectory                                          # a valid joint trajectory
geometry_msgs/TransformStamped valid_grasp_transform                                      # a valid grasp transform
int32 traj_id                                                                             #
---                                                                                       #
#feedback: optional; could declare step number of trajectory in progress,                 #
#currently there is no use for feedback                                                   #
int32 fdbk                                                                                #
                                                                                          #